name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - 5433:5432  # маппим порт контейнера 5432 на порт 5433 на хосте
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PYTHONPATH: .
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio httpx asyncpg

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
              if pg_isready -h localhost -p 5433; then
                  echo "PostgreSQL is ready"
                  exit 0
              fi
              echo "Waiting for PostgreSQL..."
              sleep 3
          done
          exit 1

      - name: Run tests
        run: pytest -s -vv --maxfail=1
